### ISSUE TITLE
add readme

### ISSUE THREAD

**Issue by junosuarez** [GSA/Open-Data-Collaboration-Sandbox#3]
Add a brief description of what's in the repo & who the intended audience is. It's got `collaboration` in the the name; any [requests for contributions](https://github.com/jden/CONTRIBUTING.md/)?

**Comment by ErieMeyer** [comment]
+1

**Comment by gbinal** [comment]
Great suggestion - thanks.  

https://github.com/GSA/Open-Data-Collaboration-Sandbox/tree/gh-pages#readme
